abbrevIndo = {
	'orang2': 'orang-orang',
	'ramai2': 'ramai-ramai',
	'rame2': 'ramai-ramai',
	'foto2': 'foto-foto',
	'ngobrol""': 'ngobrol-ngobrol',
	'temen""': 'teman-teman',
	'bener""': 'benar-benar',
	'mesen""': 'memesan',
	'd': 'di',
	'jd': 'jadi',
	'yg': 'yang',
	'dl': 'dulu',
	'tmn': 'teman',
	'dpn': 'depan',
	'sm': 'sama',
	'pd': 'pada',
	'bgt': 'banget',
	'mnrt': 'menurut',
	'dr': 'dari',
	'dri': 'dari',
	'klo': 'kalau',
	'klu': 'kalau',
	'kli': 'kali',
	'trs': 'terus',
	'blm': 'belum',
	'blom': 'belum',
	'pdhal': 'padahal',
	'pdhl': 'padahal',
	'blg': 'bilang,',
	'gt': 'begitu',
	'gn': 'begini',
	'kyk': 'kayak',
	'kyknya': 'kayaknya',
	'rb': 'ribu',
	'koq': 'kok',
	'tu': 'itu',
	'ga': 'tidak',
	'g': 'tidak',
	'tdk': 'tidak',
	'hrs': 'harus',
	'cpt': 'cepat',
	'cpet': 'cepat'
}

abbrevEng = {
	'resto': 'restaurant',
	'fave': 'favorite',
	'bcs': 'because',
	'bcoz': 'because'
}
